### ISSUE TITLE
Wiki TODO

### ISSUE THREAD

**Issue by bvernoux** [hydrausb3/hydrausb3_fw#6]
Wiki TODO:
- [x] [hydrausb3_fw README.md](https://github.com/hydrausb3/hydrausb3_fw/blob/main/README.md) updated about Toolchains Build
    - [x] How to build the firmware source code for HydraUSB3(CH569 MCU) with MounRiver Studio(Eclipse based) IDE
       - [x] Add MRS_Toolchain_Linux_x64_V1.50(Toolchain&Debugger)
    - [x] How to build the firmware source code for HydraUSB3(CH569 MCU) with shell
       - [x] Windows 10 x64 + MounRiver Studio V181 / MounRiver Studio Community Win V120 with [MSYS2/MINGW64](https://www.msys2.org/)
       - [x] Linux + MounRiver_Studio_Community_Linux_x64_V120(RISC-V IDE Community)
       - [x] Linux + MRS_Toolchain_Linux_x64_V1.50(Toolchain&Debugger)
    - [x] To be dispatched in Wiki(s)
- [ ] [Home](https://github.com/hydrausb3/hydrausb3_fw/wiki)
- [ ] [Getting-Started-with-HydraUSB3](https://github.com/hydrausb3/hydrausb3_fw/wiki/Getting-Started-with-HydraUSB3)
- [x] [How to build flash and use examples on Linux](https://github.com/hydrausb3/hydrausb3_fw/wiki/how-to-build-flash-and-use-examples-on-linux)
    - [x] MounRiver_Studio_Community_Linux_x64
    - [x] MRS_Toolchain_Linux_x64
- [x] [How to build flash and use examples on Windows](https://github.com/hydrausb3/hydrausb3_fw/wiki/how-to-build-flash-and-use-examples-on-windows)
    - [x] MounRiver_Studio / MounRiver_Studio_Community
